#!/usr/bin/env php
<?php

use Config\CoreConfigFactory;
use Config\Dependencies\DependencyBindings;
use Config\Events\EventRegistration;
use MissionControlBackend\Boot;

require __DIR__ . '/vendor/autoload.php';

(new Boot())
    ->start((new CoreConfigFactory)->create())
    ->buildContainer([DependencyBindings::class, 'register'])
    ->registerEvents([EventRegistration::class, 'register'])
    ->buildCliApplication()
    ->applyCommands()
    ->runApplication();
