#!/usr/bin/env php
<?php

use MissionControlBackend\Boot;

require __DIR__ . '/vendor/autoload.php';

(new Boot())
    ->start(devMode: true)
    ->registerEvents()
    ->buildContainer()
    ->buildCliApplication()
    ->applyCommands()
    ->run();
