version: '3.8'

services:
  backend:
    restart: always
    environment:
      - ENABLE_PHP_DEV_CONFIG=1
      - ENABLE_XDEBUG=1
    container_name: mission_control_backend
    healthcheck:
      disable: true
    volumes:
      - ./backend/.bash_history:/root/.bash_history:delegated
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers
    labels:
      ## Traefik config ##
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default
      # API
      - traefik.http.routers.mission_control_api.entrypoints=web
      - traefik.http.routers.mission_control_api.rule=Host(`api.mission-control.localtest.me`)
      - traefik.http.routers.mission_control_api.middlewares=https-redirect
      - traefik.http.routers.mission_control_api-secure.entrypoints=websecure
      - traefik.http.routers.mission_control_api-secure.tls=true
      - traefik.http.routers.mission_control_api-secure.rule=Host(`api.mission-control.localtest.me`)
      # Auth
      - traefik.http.routers.mission_control_auth.entrypoints=web
      - traefik.http.routers.mission_control_auth.rule=Host(`auth.mission-control.localtest.me`)
      - traefik.http.routers.mission_control_auth.middlewares=https-redirect
      - traefik.http.routers.mission_control_auth-secure.entrypoints=websecure
      - traefik.http.routers.mission_control_auth-secure.tls=true
      - traefik.http.routers.mission_control_auth-secure.rule=Host(`auth.mission-control.localtest.me`)
      # Auth
      - traefik.http.routers.mission_control_account.entrypoints=web
      - traefik.http.routers.mission_control_account.rule=Host(`account.mission-control.localtest.me`)
      - traefik.http.routers.mission_control_account.middlewares=https-redirect
      - traefik.http.routers.mission_control_account-secure.entrypoints=websecure
      - traefik.http.routers.mission_control_account-secure.tls=true
      - traefik.http.routers.mission_control_account-secure.rule=Host(`account.mission-control.localtest.me`)
    networks:
      traefik:
      default:
        aliases:
          - api.mission-control.localtest.me
          - auth.mission-control.localtest.me

  queue-consumer-default-1:
    restart: always
    container_name: queue-consumer-default-1
    volumes:
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers

  queue-consumer-email-1:
    restart: always
    container_name: queue-consumer-email-1
    volumes:
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers

  queue-consumer-url-monitoring-1:
    restart: always
    container_name: queue-consumer-url-monitoring-1
    volumes:
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers

  queue-consumer-pings-1:
    restart: always
    container_name: queue-consumer-pings-1
    volumes:
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers

  backend-scheduler:
    restart: always
    container_name: mission_control_backend_scheduler
    volumes:
      - ../backend:/var/www:delegated
      - ../../backend-core:/backend-core
      - ../../idp:/idp
      - ../../url-monitoring:/url-monitoring
      - ../../pings:/pings
      - ../../servers:/servers

  db:
    restart: always
    container_name: mission_control_db
    healthcheck:
      disable: true
    volumes:
      - ./db/.bash_history:/root/.bash_history:delegated
    ports:
      - "56936:5432"

  mailhog:
    container_name: mission_control_mailhog
    image: 'mailhog/mailhog:v1.0.1'
    user: root
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:8027
      - MH_UI_BIND_ADDR=0.0.0.0:8027
    expose:
      - 8027
    ports:
      - "8027:8027"
    networks:
      traefik:
      default:
        aliases:
          - mission_control_mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - mailhog-data-volume:/maildir
    labels:
      - traefik.enable=true
      - traefik.port=8027
      - traefik.docker.network=traefik-dev_default
      - traefik.http.routers.mosaic_portal_mailhog.entrypoints=web
      - traefik.http.routers.mosaic_portal_mailhog.rule=Host(`mailhog.mission-control.localtest.me`)
      - traefik.http.routers.mosaic_portal_mailhog.middlewares=https-redirect
      - traefik.http.routers.mosaic_portal_mailhog-secure.entrypoints=websecure
      - traefik.http.routers.mosaic_portal_mailhog-secure.tls=true
      - traefik.http.routers.mosaic_portal_mailhog-secure.rule=Host(`mailhog.mission-control.localtest.me`)
      - traefik.http.services.mosaic_portal_mailhog-secure.loadbalancer.server.port=8027

  frontend:
    restart: always
    environment:
      - ENABLE_PHP_DEV_CONFIG=1
      - ENABLE_XDEBUG=1
    container_name: mission_control_frontend
    healthcheck:
      disable: true
    volumes:
      - ./frontend/.bash_history:/root/.bash_history:delegated
      - ../frontend:/var/www:delegated
      - ../../frontend-core:/frontend-core
    labels:
      ## Traefik config ##
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default

      - traefik.http.routers.mission_control_web.entrypoints=web
      - traefik.http.routers.mission_control_web.rule=Host(`mission-control.localtest.me`)
      - traefik.http.routers.mission_control_web.middlewares=https-redirect
      - traefik.http.routers.mission_control_web-secure.entrypoints=websecure
      - traefik.http.routers.mission_control_web-secure.tls=true
      - traefik.http.routers.mission_control_web-secure.rule=Host(`mission-control.localtest.me`)
    networks:
      traefik:
      default:
        aliases:
          - mission-control.localtest.me

networks:
  traefik:
    name: traefik-dev_default
    external: true

volumes:
  mailhog-data-volume:
