version: '3.8'

services:
  backend:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    image: ghcr.io/buzzingpixel-mission-control/mission-control-backend
    environment:
      - HOSTNAME=mission_control_backend
    networks:
      - default

  redis:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    container_name: mission_control_redis
    image: redis:6.2.10-alpine3.17
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - mission_control_redis

volumes:
  redis:
