version: '3.8'

services:
  backend:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    image: ghcr.io/buzzingpixel-mission-control/mission-control-backend
    environment:
      - HOSTNAME=mission_control_backend
    networks:
      - default

  redis:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    container_name: mission_control_redis
    image: redis:6.2.10-alpine3.17
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - mission_control_redis

  queue-consumer-default-1:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    image: ghcr.io/buzzingpixel-mission-control/mission-control-backend
    environment:
      - HOSTNAME=queue-consumer-default-1
    networks:
      - default
    entrypoint: >-
      /bin/bash -c
      "echo 'while /usr/local/bin/php /var/www/cli buzzingpixel-queue:consume-next --verbose --no-interaction 2>&1; do sleep 1; done' > /runner.sh
      && chmod +x /runner.sh
      && /runner.sh"

  queue-consumer-email-1:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    image: ghcr.io/buzzingpixel-mission-control/mission-control-backend
    environment:
      - HOSTNAME=queue-consumer-email-1
    networks:
      - default
    entrypoint: >-
      /bin/bash -c
      "echo 'while /usr/local/bin/php /var/www/cli buzzingpixel-queue:consume-next --queue-name=email --verbose --no-interaction 2>&1; do sleep 1; done' > /runner.sh
      && chmod +x /runner.sh
      && /runner.sh"

  backend-scheduler:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    image: ghcr.io/buzzingpixel-mission-control/mission-control-backend
    environment:
      - HOSTNAME=mission_control_backend_scheduler
    networks:
      - default
    healthcheck:
      test: ["CMD", "php", "/var/www/cli"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10
    entrypoint: >-
      /bin/bash -c
      "echo 'while php /var/www/cli buzzingpixel-schedule:run --verbose --no-interaction 2>&1; do sleep 60; done' > /runner.sh
      && chmod +x /runner.sh
      && /runner.sh"

  db:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./db/.env
      - ./db/.env.local
    image: postgres:15.2
    environment:
      HOSTNAME: mission_control_db
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - mission_control_db

volumes:
  db-volume:
  redis:
